/*
-- Query: select day(RESCUEDATE) from PETRESCUE
LIMIT 0, 1000

-- Date: 2024-01-31 13:15
*/
INSERT INTO `` (`day(RESCUEDATE)`) VALUES (29);
INSERT INTO `` (`day(RESCUEDATE)`) VALUES (1);
INSERT INTO `` (`day(RESCUEDATE)`) VALUES (4);
INSERT INTO `` (`day(RESCUEDATE)`) VALUES (4);
INSERT INTO `` (`day(RESCUEDATE)`) VALUES (10);
INSERT INTO `` (`day(RESCUEDATE)`) VALUES (11);
INSERT INTO `` (`day(RESCUEDATE)`) VALUES (11);
INSERT INTO `` (`day(RESCUEDATE)`) VALUES (14);
INSERT INTO `` (`day(RESCUEDATE)`) VALUES (15);
