/*
-- Query: SELECT from_days(DATEDIFF(CURRENT_DATE, RESCUEDATE)) FROM PETRESCUE
LIMIT 0, 1000

-- Date: 2024-01-31 13:24
*/
INSERT INTO `` (`from_days(DATEDIFF(CURRENT_DATE, RESCUEDATE))`) VALUES ('0005-09-04');
INSERT INTO `` (`from_days(DATEDIFF(CURRENT_DATE, RESCUEDATE))`) VALUES ('0005-09-01');
INSERT INTO `` (`from_days(DATEDIFF(CURRENT_DATE, RESCUEDATE))`) VALUES ('0005-08-29');
INSERT INTO `` (`from_days(DATEDIFF(CURRENT_DATE, RESCUEDATE))`) VALUES ('0005-08-29');
INSERT INTO `` (`from_days(DATEDIFF(CURRENT_DATE, RESCUEDATE))`) VALUES ('0005-08-23');
INSERT INTO `` (`from_days(DATEDIFF(CURRENT_DATE, RESCUEDATE))`) VALUES ('0005-08-22');
INSERT INTO `` (`from_days(DATEDIFF(CURRENT_DATE, RESCUEDATE))`) VALUES ('0005-08-22');
INSERT INTO `` (`from_days(DATEDIFF(CURRENT_DATE, RESCUEDATE))`) VALUES ('0005-08-19');
INSERT INTO `` (`from_days(DATEDIFF(CURRENT_DATE, RESCUEDATE))`) VALUES ('0005-08-18');
