/*
-- Query: select month(RESCUEDATE) from PETRESCUE
LIMIT 0, 1000

-- Date: 2024-01-31 13:16
*/
INSERT INTO `` (`month(RESCUEDATE)`) VALUES (5);
INSERT INTO `` (`month(RESCUEDATE)`) VALUES (6);
INSERT INTO `` (`month(RESCUEDATE)`) VALUES (6);
INSERT INTO `` (`month(RESCUEDATE)`) VALUES (6);
INSERT INTO `` (`month(RESCUEDATE)`) VALUES (6);
INSERT INTO `` (`month(RESCUEDATE)`) VALUES (6);
INSERT INTO `` (`month(RESCUEDATE)`) VALUES (6);
INSERT INTO `` (`month(RESCUEDATE)`) VALUES (6);
INSERT INTO `` (`month(RESCUEDATE)`) VALUES (6);
