/*
-- Query: select year(RESCUEDATE) from PETRESCUE
LIMIT 0, 1000

-- Date: 2024-01-31 13:15
*/
INSERT INTO `` (`year(RESCUEDATE)`) VALUES (2018);
INSERT INTO `` (`year(RESCUEDATE)`) VALUES (2018);
INSERT INTO `` (`year(RESCUEDATE)`) VALUES (2018);
INSERT INTO `` (`year(RESCUEDATE)`) VALUES (2018);
INSERT INTO `` (`year(RESCUEDATE)`) VALUES (2018);
INSERT INTO `` (`year(RESCUEDATE)`) VALUES (2018);
INSERT INTO `` (`year(RESCUEDATE)`) VALUES (2018);
INSERT INTO `` (`year(RESCUEDATE)`) VALUES (2018);
INSERT INTO `` (`year(RESCUEDATE)`) VALUES (2018);
